
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ECEN3002_Project1(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		          		VGA_CLK,
	output		          		VGA_SYNC_N,
	output		          		VGA_HS,
	output		          		VGA_VS,
	output		     [7:0]		VGA_R,
	output		     [7:0]		VGA_G,
	output		     [7:0]		VGA_B
);

assign VGA_BLANK_N = 1'b1;
assign VGA_SYNC_N = 1'b0;

wire pixel_clk;
wire locked_wire;
wire [9:0] h_pos;
wire [9:0] v_pos;

// bring in PLL clock
video_pll VP0(.refclk(CLOCK2_50), .rst(1'b0), .outclk_0(pixel_clk), .locked(locked_wire));

assign VGA_CLK = pixel_clk;

// KEY[0] reset
assign reset_n = KEY[0] & locked_wire;

VTC VTC0(.pixel_clk(pixel_clk), .reset_n(reset_n), .h_pos(h_pos), .v_pos(v_pos), .VGA_HS(VGA_HS), .VGA_VS(VGA_VS));
PG PG0(.KEY(KEY), .SW(SW), .pixel_clk(pixel_clk), .h_pos(h_pos), .v_pos(v_pos), .VGA_R(VGA_R), .VGA_G(VGA_G), .VGA_B(VGA_B));

endmodule
